### PR TITLE
First version

### PR DESCRIPTION
**Pull request by MarcosCM**

### CODE REVIEW

**Comment by fjlopez** [comment]
There are more issues with other files

**Comment by fjlopez** [comment]
Let me check what is happening.

**Comment by fjlopez** [comment]
I think that I merged well the code but please check it.

**Comment by MarcosCM** [comment]
It seems that GitHub is having some issues.
https://status.github.com/

**Comment by MarcosCM** [comment]
I have just checked the code. Everything is right except a single file, the [SecurityContextHolderUtils](https://github.com/UNIZAR-30246-WebEngineering/UrlShortener2015/blob/heat-wave/heat-wave/src/main/java/urlshortener2015/heatwave/utils/SecurityContextUtils.java)
Line 44: it should be a NOT equals, like this:
```
if (!authAs.equals("anonymousUser")){
```
You can modify it by yourself. I will do at least another pull request in the next days, so it does not matter at the moment.

**Comment by fjlopez** [comment]
Ok, fixed!

**Pull request merged**
